spring.application.name=springDataJpa

# Para criar o Banco de dados no Mysql e conectar com sua api
spring.datasource.url=jdbc:mysql://localhost:3306/gym?createDatabaseIfNotExist=true
## Para pegar o usurious do Banco de dados numa variable de ambient
spring.datasource.username=${DATABASE_USERNAME}
# Para pegar a senha do Banco de dados numa variable de ambient
spring.datasource.password=${DATABASE_PASSWORD}

#Sempre actualize as tablas do Banco de dados
spring.jpa.hibernate.ddl-auto=update


# Para ver como as querys ta no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
